export type ChannelDetails = {
    channelUrl: string,
    createdBy: string,
    views: string,
    likes: string,
    numVideos: string,
    followers: string,
    followPoints: string,
    points: string,
    imageUser: string,
    image: string,
    coverPhoto: string,
    days: string,
    cover: string,
    title: string,
    description: string,
    id: string,
    privacy: string,
    is_recommended: string,
    is_moderator: string,
    createdOn: string,
    user_id: string,
    name: string,
    thumbnail: string,
    ownerRank: string,
    ownerJoined: string
}